#! /bin/sh
### BEGIN INIT INFO
# Provides:          mizram
# Required-Start:    $local_fs
# Required-Stop:     $local_fs
# Should-Start:
# Should-Stop:
# X-Start-Before:
# X-Stop-After:
# Default-Start:     S
# Default-Stop:      0 1 6
# Short-Description: mizram
# Description:       mizram
### END INIT INFO

case "$1" in
  start)
	modprobe zram num_devices=1
	zramctl -f -t 2 -s 100MB -a lz4
	mkswap /dev/zram0
	swapon --priority 10 /dev/zram0
	;;
  stop)
	swapoff /dev/zram0
	wait
        sleep .5
        modprobe --remove zram
	;;
  *)
	echo "Usage: $SCRIPTNAME {start|stop|restart|force-reload|status}"
	exit 1
	;;
esac

exit 0
