#!/usr/bin/env bash
# Made by Sinfallas <sinfallas@yahoo.com>
# Licence: GPL-2
set -eu
LC_ALL=C
if [[ "$EUID" != "0" ]]; then
	echo -e "\e[00;31mERROR: DEBES SER ROOT\e[00m"
	exit 1
fi
echo "always" > /sys/kernel/mm/transparent_hugepage/enabled
echo "20000" > /sys/kernel/mm/transparent_hugepage/khugepaged/pages_to_scan
echo -e "\e[00;1;92mFinished...\e[00m"
exit 0
