#!/usr/bin/env bash
# Made by Sinfallas <sinfallas@yahoo.com>
# Licence: GPL-2
set -eu
LC_ALL=C
if [[ "$EUID" != "0" ]]; then
	echo -e "\e[00;31mERROR: DEBES SER ROOT\e[00m"
	exit 1
fi

modprobe zram num_devices=1
zramctl -f -t 2 -s 100MB -a lz4
mkswap /dev/zram0
swapon --priority 10 /dev/zram0
echo -e "\e[00;1;92mFinalizado...\e[00m"
exit 0
